name: Create Test build to `main/test/` folder

on:
  push:
    branches:
      - main

jobs:
  build-and-push-to-main-test-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # нужен полный fetch для коммитов

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create tar.gz archive
        run: |
          mkdir -p output
          cd scripts
          chmod +x xkeen
          find . -type f -o -type l | sed 's|^\./||' | tar -czf "../output/xkeen.tar.gz" -T -

      - name: Move archive to test folder in main
        run: |
          mkdir -p test
          mv output/xkeen.tar.gz test/

      - name: Commit and push archive to test folder
        run: |
          git add test/xkeen.tar.gz
          git commit -m "[github-actions] automated compiling build" || echo "No changes"
          git push origin main
